# Social Media Platform Configuration
server:
  port: "8084"
  base_url: "https://test-pubproject.wondera.io"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

platform:
  supported_providers:
    - "youtube"
    - "x"
    - "facebook"
    - "tiktok"
    - "instagram"

# 多项目配置
# 每个项目可以有自己独立的OAuth配置
servers:
  wondera:
    youtube:
      client_id: "${GOOGLE_CLIENT_ID}"
      client_secret: "${GOOGLE_CLIENT_SECRET}"
      scopes:
        - "https://www.googleapis.com/auth/youtube.upload"
        - "openid"
        - "email"
    x:
      client_id: "${X_CLIENT_ID}"
      client_secret: "${X_CLIENT_SECRET}"
      scopes:
        - "tweet.read"
        - "tweet.write"
        - "users.read"
        - "offline.access"
    tiktok:
      client_id: "${TIKTOK_CLIENT_ID}"
      client_secret: "${TIKTOK_CLIENT_SECRET}"
      scopes:
        - "user.info.basic"
        - "video.upload"
    facebook:
      client_id: "${FACEBOOK_CLIENT_ID}"
      client_secret: "${FACEBOOK_CLIENT_SECRET}"
      scopes:
        - "pages_manage_posts"
        - "pages_read_engagement"
        - "pages_show_list"
        - "pages_read_user_content"
    instagram:
      client_id: "${INSTAGRAM_CLIENT_ID}"
      client_secret: "${INSTAGRAM_CLIENT_SECRET}"
      scopes:
        - "instagram_content_publish"
        - "pages_read_engagement"
